field.storage_settings.gt_people_degrees:
  type: mapping
  label: 'GT People Degree storage settings'
  mapping: {}

field.field_settings.gtppl_degrees:
  type: mapping
  label: 'GT People Degrees field settings'
  mapping:
    name:
      type: string
      label: 'Degree'
    year:
      type: string
      label: 'Year'
    institution:
      type: string
      label: 'Institution'
    location:
      type: string
      label: 'Location'

field.value.gt_people_degrees:
  type: mapping
  label: 'GT People Degree value'
  mapping:
    name:
      type: string
      label: 'Degree'
    year:
      type: string
      label: 'Year'
    institution:
      type: string
      label: 'Institution'
    location:
      type: string
      label: 'Location'

field.widget.settings.gt_people_degrees_widget:
  type: mapping
  label: 'GT People Degree Widget settings'
  mapping: {}

field.formatter.settings.gt_people_degrees_formatter:
  type: mapping
  label: 'GT People Degree Formatter settings'
  mapping: {}
